[project]
name = "admin"
version = "0.0.1"
description = "Admin app"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "jinja2>=3.1.6",
    "jx>=0.5.1",
    "python-multipart>=0.0.22",
    "uvicorn[standard]>=0.40.0",
]
